import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { parseApng } from './apngParse';

/**
 * Fixtures are generated by the encoder in tools/apngEncode.mjs and embedded
 * here so the test has no dependency on the build having run. Both are 3x2
 * images: ANIM has two frames (100ms then 250ms), STATIC is the same file
 * with its acTL/fcTL chunks removed - i.e. an ordinary non-animated PNG.
 */
const ANIM_B64 =
  'iVBORw0KGgoAAAANSUhEUgAAAAMAAAACCAYAAACddGYaAAAACGFjVEwAAAACAAAAAPONk3AAAAAaZmNUTAAAAAAAAAADAAAAAgAAAAAAAAAAAGQD6AAA1rcPRQAAABFJREFUeNpj+M/A8B+GGZA5AJt+C/UPXyYiAAAAGmZjVEwAAAABAAAAAwAAAAIAAAAAAAAAAAD6A+gAACPyfOAAAAAUZmRBVAAAAAJ42mNgYPjfgMBIHABtTwj7Z39VWwAAAABJRU5ErkJggg==';
const STATIC_B64 =
  'iVBORw0KGgoAAAANSUhEUgAAAAMAAAACCAYAAACddGYaAAAAEUlEQVR42mP4z8DwH4YZkDkAm34L9Q9fJiIAAAAASUVORK5CYII=';

const PNG_SIGNATURE = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

function bytes(base64: string): Uint8Array {
  return new Uint8Array(Buffer.from(base64, 'base64'));
}

/** The 4-character type of the chunk starting at `offset`, so a rebuilt
 * frame can be checked for structure rather than just for length. */
function chunkTypeAt(png: Uint8Array, offset: number): string {
  return String.fromCharCode(png[offset + 4], png[offset + 5], png[offset + 6], png[offset + 7]);
}

function chunkTypes(png: Uint8Array): string[] {
  const view = new DataView(png.buffer, png.byteOffset, png.byteLength);
  const types: string[] = [];
  let offset = 8;
  while (offset + 8 <= png.length) {
    const type = chunkTypeAt(png, offset);
    types.push(type);
    offset += 8 + view.getUint32(offset) + 4;
    if (type === 'IEND') break;
  }
  return types;
}

describe('parseApng', () => {
  it('splits an animated PNG into one standalone PNG per frame', () => {
    const parsed = parseApng(bytes(ANIM_B64));

    expect(parsed.width).toBe(3);
    expect(parsed.height).toBe(2);
    expect(parsed.frames).toHaveLength(2);
    expect(parsed.playCount).toBe(0); // 0 = loop forever
  });

  it("reads each frame's placement, delay and compositing ops", () => {
    const [first, second] = parseApng(bytes(ANIM_B64)).frames;

    expect(first.delayMs).toBe(100);
    expect(second.delayMs).toBe(250);
    for (const frame of [first, second]) {
      expect(frame).toMatchObject({ x: 0, y: 0, w: 3, h: 2, disposeOp: 0, blendOp: 0 });
    }
  });

  it("rebuilds frames as valid PNGs, since decoding them is the browser's job", () => {
    for (const frame of parseApng(bytes(ANIM_B64)).frames) {
      expect([...frame.bytes.subarray(0, 8)]).toEqual(PNG_SIGNATURE);

      // An APNG frame's pixels arrive in fdAT chunks; they have to come back
      // out as IDAT or no image decoder will touch them.
      expect(chunkTypes(frame.bytes)).toEqual(['IHDR', 'IDAT', 'IEND']);

      // The rebuilt IHDR must describe the frame, not the whole canvas -
      // getting this wrong yields a PNG that decodes at the wrong size.
      const view = new DataView(frame.bytes.buffer, frame.bytes.byteOffset, frame.bytes.byteLength);
      expect(view.getUint32(16)).toBe(frame.w);
      expect(view.getUint32(20)).toBe(frame.h);
    }
  });

  it('frames differ, so the animation is not N copies of one image', () => {
    const [first, second] = parseApng(bytes(ANIM_B64)).frames;
    expect(Buffer.from(first.bytes).equals(Buffer.from(second.bytes))).toBe(false);
  });

  it('treats a plain PNG as a single frame, so callers need no static path', () => {
    const parsed = parseApng(bytes(STATIC_B64));

    expect(parsed.frames).toHaveLength(1);
    expect(parsed.frames[0]).toMatchObject({ x: 0, y: 0, w: 3, h: 2, delayMs: 0 });
    expect(chunkTypes(parsed.frames[0].bytes)).toEqual(['IHDR', 'IDAT', 'IEND']);
  });

  it('rejects data that is not a PNG at all', () => {
    expect(() => parseApng(new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8, 9]))).toThrow(/signature/);
  });

  it('rejects a truncated chunk rather than returning half an image', () => {
    // 100 lands inside the first IDAT's data (99..115), so the chunk header
    // promises more bytes than the file has.
    expect(() => parseApng(bytes(ANIM_B64).subarray(0, 100))).toThrow(/Truncated/);
  });
});

/**
 * The committed sprite assets are the real output of the art pipeline, so
 * parsing them is what proves the encoder and this parser agree. Asserting
 * "more than one frame" rather than an exact count keeps the test from
 * breaking every time the art is retimed.
 */
describe('the committed sprite assets', () => {
  const dir = join(__dirname, '..', '..', '..', 'public', 'sprites');

  it('are all animated and all parseable', () => {
    expect(existsSync(dir)).toBe(true);
    const files = readdirSync(dir).filter((f) => f.endsWith('.apng'));
    expect(files.length).toBeGreaterThan(0);

    for (const file of files) {
      const parsed = parseApng(new Uint8Array(readFileSync(join(dir, file))));
      expect(parsed.frames.length).toBeGreaterThan(1);
      expect(parsed.width).toBeGreaterThan(0);
      expect(parsed.height).toBeGreaterThan(0);
      for (const frame of parsed.frames) {
        expect(frame.delayMs).toBeGreaterThan(0);
        expect(frame.w).toBe(parsed.width);
        expect(frame.h).toBe(parsed.height);
      }
    }
  });

  it('include no GIF - APNG is the only animated format in this game', () => {
    expect(readdirSync(dir).filter((f) => f.endsWith('.gif'))).toEqual([]);
  });
});
